<a href="https://colab.research.google.com/github/Rajeeb321123/Pytorch/blob/master/00-pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


### Scaler

In [ ]:
scaler = torch.tensor(7)
scaler, scaler.shape, scaler.dtype

(tensor(7), torch.Size([]), torch.int64)

In [ ]:
scaler.ndim

0

### Vector

In [ ]:
vector = torch.tensor([1,2,3])
vector, vector.shape, vector.dtype

(tensor([1, 2, 3]), torch.Size([3]), torch.int64)

In [ ]:
vector.ndim

1

### Matrix

In [ ]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix, matrix.shape, matrix.dtype

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]),
 torch.int64)

In [ ]:
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float64)
matrix, matrix.shape, matrix.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]], dtype=torch.float64),
 torch.Size([3, 3]),
 torch.float64)

In [ ]:
matrix.ndim, torch.linalg.matrix_rank(matrix)

(2, tensor(2))

### Tensor

In [ ]:
tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], dtype=torch.float64)
tensor, tensor.shape, tensor.dtype

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.],
          [10., 11., 12.]]], dtype=torch.float64),
 torch.Size([2, 2, 3]),
 torch.float64)

In [ ]:
tensor.ndim, torch.linalg.matrix_rank(tensor)

(3, tensor([2, 2]))

### Changeable and unchangeable tensor

In [ ]:
changeable_tensor = torch.tensor([1,2,3])
unchangeable_tensor = torch.tensor([1,2,3], dtype=torch.float64, requires_grad=True)
changeable_tensor, unchangeable_tensor

(tensor([1, 2, 3]),
 tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True))

In [ ]:
unchangeable_tensor[0] = 4

RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

In [ ]:
changeable_tensor[0] = 4
changeable_tensor

tensor([4, 2, 3])

### Creating random tensor in pytorch

In [ ]:
torch.manual_seed(42)
random_tensor = torch.rand(3,4)

torch.manual_seed(52)
random_tensor_2 = torch.rand(3,4)
random_tensor, random_tensor_2, random_tensor == random_tensor_2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### Shuffling

In [ ]:
torch.manual_seed(42)
not_shuffled = torch.rand(3,4)
print(not_shuffled.size(0))

torch.manual_seed(42)
indices = torch.randperm(not_shuffled.size(0)) # 3 frin shape (3,4)
shuffled = not_shuffled[indices]
not_shuffled, shuffled


3


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.9408, 0.1332, 0.9346, 0.5936],
         [0.3904, 0.6009, 0.2566, 0.7936]]))

In [ ]:
torch.manual_seed(42)
indices = torch.randperm(not_shuffled.size(0)) # 3 frin shape (3,4)
shuffled = not_shuffled[indices]
shuffled

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.3904, 0.6009, 0.2566, 0.7936]])

### Other way

In [ ]:
ones_tensor = torch.ones(3,4)
zeros_tensor = torch.zeros(3,4)
ones_tensor, zeros_tensor

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

### Numpy to Torch

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tensor = torch.tensor(numpy_A, dtype=torch.float32) # create a PyTorch tensor from NumPy array
tensor, tensor.shape, tensor.dtype


(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24.]),
 torch.Size([24]),
 torch.float32)

In [ ]:
tensor.numpy(),np.array(tensor)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
       dtype=float32),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
       dtype=float32))

### Reshaping tensor

In [ ]:
tensor = torch.tensor([1,2,3,4])
tensor, tensor.shape, tensor.view(2,2), tensor.reshape(2,2) # use reshape -> more flexible

(tensor([1, 2, 3, 4]),
 torch.Size([4]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

## Getting information from Tensor

In [ ]:
rank_5_tensor = torch.zeros(size=(2,3,4,5,6))
rank_5_tensor

tensor([[[[[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]]],


         [[[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0.

In [ ]:
rank_5_tensor.ndim, rank_5_tensor.shape, rank_5_tensor.dtype

(5, torch.Size([2, 3, 4, 5, 6]), torch.float32)

In [ ]:
print("Datatype of every element:", rank_5_tensor.dtype)
print("Number of dimensions (rank):", rank_5_tensor.ndim)
print("shape of tensor:", rank_5_tensor.shape)
print("Elements along the 0 axis:", rank_5_tensor.shape[0])
print("Elements along the last axis:", rank_5_tensor.shape[-1])
print("the total number of elements in our tensor:", rank_5_tensor.numel())


Datatype of every element: torch.float32
Number of dimensions (rank): 5
shape of tensor: torch.Size([2, 3, 4, 5, 6])
Elements along the 0 axis: 2
Elements along the last axis: 6
the total number of elements in our tensor: 720


In [ ]:
rank_5_tensor[0]

tensor([[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0

### Indexing tensor

In [ ]:
rank_5_tensor[:,0,2:3]

tensor([[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]])

### Basic Operation

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10, tensor - 10, tensor * 10, tensor / 10

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

#### Matrix multiplicaiton

In [ ]:
tensor = torch.tensor([[1,2],[4,5]])

tensor @ tensor, torch.matmul(tensor, tensor)


(tensor([[ 9, 12],
         [24, 33]]),
 tensor([[ 9, 12],
         [24, 33]]))

### Changing data type

In [ ]:
tensor = torch.tensor([1,2,3], dtype=torch.float32)
print(tensor.dtype)
tensor = tensor.type(torch.int32)
print(tensor.dtype)
tensor = tensor.to(torch.float64)
print(tensor.dtype)

torch.float32
torch.int32
torch.float64


### Aggregating tensor

In [ ]:
tensor = torch.tensor([1,-2,-3], dtype=torch.float32)
tensor.abs(), tensor.min(), tensor.max(), tensor.mean(), tensor.sum(), tensor.argmin(), tensor.argmax()

(tensor([1., 2., 3.]),
 tensor(-3.),
 tensor(1.),
 tensor(-1.3333),
 tensor(-4.),
 tensor(2),
 tensor(0))

#### Variance & Standard Deviation

In [ ]:
tensor = torch.tensor([[1,2,3],[1,2,4]], dtype=float) # for variance and std shape doesnot matter
tensor.var(), tensor.std()

(tensor(1.3667, dtype=torch.float64), tensor(1.1690, dtype=torch.float64))

### Squaring, Log, Square root

In [ ]:
tensor = torch.range(0,10)
tensor

<ipython-input-121-03512ef968c3>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
tensor.square(), torch.square(tensor), tensor**2,torch.pow(tensor, 2), torch.sqrt(tensor.float())

(tensor([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.]),
 tensor([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.]),
 tensor([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.]),
 tensor([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.]),
 tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284,
         3.0000, 3.1623]))

### Squeezing tensor (removing single dimension)

In [ ]:
tensor = torch.rand(50)
tensor

tensor([0.4452, 0.1258, 0.9554, 0.1330, 0.7672, 0.6757, 0.6625, 0.2297, 0.9545,
        0.6099, 0.5643, 0.0594, 0.7099, 0.4250, 0.2709, 0.9295, 0.6115, 0.2234,
        0.2469, 0.4761, 0.7792, 0.3722, 0.2147, 0.3288, 0.1265, 0.6783, 0.8870,
        0.0293, 0.6161, 0.7583, 0.5907, 0.3219, 0.7610, 0.7628, 0.6870, 0.4121,
        0.3676, 0.5535, 0.4117, 0.3510, 0.8196, 0.9297, 0.4505, 0.3881, 0.5073,
        0.4701, 0.6202, 0.6401, 0.0459, 0.3155])

In [ ]:
torch.manual_seed(42)
tensor = torch.rand(1,1,1,50)
tensor

tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
           0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294,
           0.8854, 0.5739, 0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317,
           0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753,
           0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423,
           0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895,
           0.7539, 0.1952]]]])

In [ ]:
torch.manual_seed(42)
tensor = torch.rand(50).view(1,1,1,50)  # View is to reshape the tensor
tensor, tensor.shape

(tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
            0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294,
            0.8854, 0.5739, 0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317,
            0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753,
            0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423,
            0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895,
            0.7539, 0.1952]]]]),
 torch.Size([1, 1, 1, 50]))

In [ ]:
tensor.squeeze(), tensor.squeeze().shape

(tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
         0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
         0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588,
         0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090,
         0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890,
         0.2814, 0.7886, 0.5895, 0.7539, 0.1952]),
 torch.Size([50]))

### Unsqueezing in torch ( similar to tf.expand in tensorflow)

In [ ]:
import torch

# Create a 1D tensor
X = torch.tensor([1, 2, 3, 4])

# Expand dimensions
X_expanded = X.unsqueeze(-1)

print("Original Tensor:", X)
print("Expanded Tensor:", X_expanded)

In [ ]:
import torch

# Create a 2D tensor
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

print("Original Tensor:", X)

# Expand dimension at first position
X_expanded_first = X.unsqueeze(0)
# Expand dimensions at the second position (axis=1)
X_expanded_second = X.unsqueeze(1)
# Expand dim at last position
X_expanded_last = X.unsqueeze(-1)


print("Expanded Tensor at the first position:", X_expanded_first)
print("Expanded Tensor at the second position:", X_expanded_second)
print("Expanded Tensor at the last position:", X_expanded_last)

## One Hot Encoding

In [ ]:
some_list = [0,1,2,3,4,5]
tensor = torch.nn.functional.one_hot(torch.tensor(some_list), num_classes=6)
tensor

tensor([[1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1]])

In [ ]:
torch.tensor(some_list)

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
tensor = torch.nn.functional.one_hot(torch.tensor(some_list), num_classes=7)
tensor

tensor([[1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0]])

In [ ]:
torch.arange(0, 6).view(3,2) % 3

tensor([[0, 1],
        [2, 0],
        [1, 2]])

In [ ]:
torch.nn.functional.one_hot(torch.arange(0, 6).view(3,2) % 3, num_classes=3)

tensor([[[1, 0, 0],
         [0, 1, 0]],

        [[0, 0, 1],
         [1, 0, 0]],

        [[0, 1, 0],
         [0, 0, 1]]])